### ISSUE TITLE
[Feature request] Add PayPal billing support

### ISSUE THREAD

**Issue by MrLotU** [vapor-cloud/roadmap#33]
To allow for more people to use payed services from the Cloud project, it'd be nice to be able to pay with PayPal instead of just Credit Card

**Comment by joscdk** [comment]
We don't have any plans now, but i will take it up for internal discussion if it's something we should consider adding.

**Comment by joscdk** [comment]
Because of some concerns with PayPal, and the risk of accounts being frozen, we unfortunately can't prioritise this. At least not at this point and at the size we have now.
We might want to look into this later if our situation changes in the future.

We will however still implement a credit system, so it's possible to add $X into the account that will be used to pay invoices.
