### ISSUE TITLE
[Feature request] List current running git commit hash on application page

### ISSUE THREAD

**Issue by MrLotU** [vapor-cloud/roadmap#39]
Personally, I'd love to have a quick and easy way to see what exact git commit my app is running at on the dashboard.

I mocked up 2 small designs (see screenshots)
<img width="457" alt="screenshot 2019-01-04 at 15 42 17" src="https://user-images.githubusercontent.com/18392003/50693647-dc7dfa00-1037-11e9-955b-21c6c5979836.png">
<img width="1402" alt="screenshot 2019-01-04 at 15 44 29" src="https://user-images.githubusercontent.com/18392003/50693648-dc7dfa00-1037-11e9-8ff7-39d54a5e3831.png">

**Comment by joscdk** [comment]
Hi @MrLotU 

As written on Discord, thanks for this, it's a really good idea, and we will try to get it implemented asap. And will start this shortly after the release lists are up.

One note though, because of the nature of data collection and the association of data, this will either be part of the `Application` or `Git` card, and not the `Replica(s)` card .. The Git card might make most sense, but we will see where it fits in later :)
